/*
 * stm32f407xx_I2C_driver.c
 *
 *  Created on: 17-Jan-2025
 *      Author: vibhu
 */

#include <stm32f4xx_I2C_driver.h>
#include <stm32f407xx.h>

static void I2CMasterHandleTXEInterrupt(I2C_handle_t *pI2Chandle);
static void EnDi_Interrupts(I2C_RegDef_t *pI2Cx , uint8_t EnDi);
static void I2C_Gen_Start(I2C_RegDef_t *pI2Cx);
static void I2C_ExecuteAddressPhase(I2C_RegDef_t *pI2Cx,uint8_t SlaveAddr);
static void I2C_ExecuteAddressPhaseRead(I2C_RegDef_t *pI2Cx,uint8_t SlaveAddr);
static void ClearAddrFlag(I2C_handle_t *pI2Chandle);
static void I2CMasterHandleRXNEInterrupt(I2C_handle_t *pI2Chandle);
static void I2C_Gen_Stop(I2C_RegDef_t *pI2Cx);
static void I2C_CloseReceiveData(I2C_handle_t *pI2Chandle);
static void I2C_CloseSendData(I2C_handle_t* pI2Chandle);
uint16_t factor_AHB[] ={2,4,8,16,64,128,256,512};
uint8_t factor_APB1[] ={2,4,8,16};
uint32_t getPCLK1Freq() // pg 154 of reference manual
{

	//clk sources can be HSE,HSI OR PLLCLK
	//whatever clock is selected is prescaled by AHB prescaler and then APB prescaler

	//clk source
	uint32_t SystemClk;

	uint8_t clksource = ((RCC->RCC_CFGR >> 2) & 0x03); // gives value of SWS0 AND SWS1

	if(clksource ==0)
	{
		SystemClk = 16000000;
	}
	else if(clksource == 1)
	{
		SystemClk = 8000000;
	}
	//No support for PLL

	//Now get the value of AHB prescaler

	uint8_t AHBprescalefactor =((RCC->RCC_CFGR >> 4) & 0x0f);

	if(AHBprescalefactor < 8)
	{
		SystemClk = SystemClk/1;
	}
	else if(AHBprescalefactor >=8)
	{
		SystemClk = SystemClk/(factor_AHB[8 - AHBprescalefactor]);
	}
	//As all I2C peripherals are connected to apb1 BUS
	uint8_t APB1_prescaler = (RCC->RCC_CFGR >> 10) & 0x07; //extract the the bits for prescaler factor

	if(APB1_prescaler<4)
	{
		SystemClk = SystemClk/1;
	}
	else if(APB1_prescaler>=4)
	{
		SystemClk = SystemClk/(factor_APB1[APB1_prescaler - 4]);
	}




	return(SystemClk);
}
void I2C_Peripehral_clk_control(I2C_RegDef_t *I2Cpx,uint8_t EnDi)
{
	if(EnDi == ENABLE)
	{
		if(I2Cpx == I2C1 )
		{
			I2C1_PCLK_EN();
		}
		else if (I2Cpx == I2C2)
		{
			I2C2_PCLK_EN();
		}
		else if (I2Cpx == I2C3)
		{
			I2C3_PCLK_EN();
		}
	}
	else if(EnDi == DISABLE)
	{
		if(I2Cpx == I2C1 )
		{
			I2C1_PCLK_EN();
		}
		else if (I2Cpx == I2C2)
		{
			I2C2_PCLK_EN();
		}
		else if (I2Cpx == I2C3)
		{
			I2C3_PCLK_EN();
		}
	}
}
void I2C_EnDi(I2C_RegDef_t *pI2Cx , uint8_t EnDi)
{
	if(EnDi == ENABLE)
	{
		pI2Cx->I2C_CR1|=(1<<I2C_PE);
	}
	else if (EnDi == DISABLE)
	{
		pI2Cx->I2C_CR1 &=~(1<<I2C_PE);
	}
}
void I2C_init(I2C_handle_t *pI2Chandle)
{
	I2C_Peripehral_clk_control(pI2Chandle->pI2Cx,ENABLE);
	uint32_t tempreg = 0;
	tempreg |= (pI2Chandle->I2C_config_params.I2C_ACKControl << I2C_ACK);
	pI2Chandle->pI2Cx->I2C_CR1 = tempreg;
	uint32_t k = getPCLK1Freq(); // get clock  frequency at which APB1 bus is operating

	//configure freq field
	uint8_t freq;
	if(k>1000000 && k <= 42000000)// pclk freq should be less than 42 MHz
	{
		freq = k/1000000U; // to get clock in MHZ therefore freq is in the range of 1 to 42 Mhz
		pI2Chandle->pI2Cx->I2C_CR2 |=((freq & 0x3f) << 0);
	}

	// store slave 7 bit OAR1 register and configure OAR1 register check the register layout in reference manual
	tempreg=0;
	tempreg |= (pI2Chandle->I2C_config_params.DeviceAddress << 1);
	tempreg |= (1<<14); //as per the reference manual
	tempreg &=~(1<<15);
	pI2Chandle->pI2Cx->I2C_OAR1 = tempreg;
	tempreg=0;
	//CCR calculations - 191
	uint16_t ccr_value=0;

	if(pI2Chandle->I2C_config_params.I2C_SCLSpeed <= I2C_SCL_SPEED_SM) // then configure the ccr to operate in SM
	{
		//mode SM ie 15th bit in CCR reg
		//pI2Chandle->pI2Cx->I2C_CCR&=~(1<<15); //configure the 15th bit from SM
		//if Thigh == Tlow 50% duty then Tscl = 2*CCR *Tpclk1 therefore ccr = Tscl/2*Tpclk1
		// ccr = Fpclk1 / 2*Fscl
		ccr_value = k / (2 * pI2Chandle->I2C_config_params.I2C_SCLSpeed);
		tempreg|=(ccr_value & 0xfff); // as CCR value is 12 bit
	}
	else
	{
		tempreg|=(1<<15);
		tempreg|=(pI2Chandle->I2C_config_params.I2C_FMDutyCycle << 14);
		if(pI2Chandle->I2C_config_params.I2C_FMDutyCycle == I2C_FM_DUTY_2)
		{
			ccr_value = k / (3 * pI2Chandle->I2C_config_params.I2C_SCLSpeed);

		}
		else
		{
			ccr_value = k / (25 * pI2Chandle->I2C_config_params.I2C_SCLSpeed);
		}
		tempreg|=(ccr_value & 0xfff);

	}
	pI2Chandle->pI2Cx->I2C_CCR= tempreg;
	//trise register left
	//[Fpclk1 * Trise(max)] + 1
	tempreg=0;
	if(pI2Chandle->I2C_config_params.I2C_SCLSpeed <= I2C_SCL_SPEED_SM)
	{
		tempreg= (k/1000000U) + 1;
	}
	else
	{
		tempreg= ((k*300)/1000000000U) + 1;
	}
	pI2Chandle->pI2Cx->I2C_TRISE = (tempreg & 0x3f);

}
void I2C_MasterSendData(I2C_handle_t *pI2Chandle, uint8_t *pTxBuffer ,uint32_t Len, uint8_t SlaveAddr , uint8_t rep_start)
{
	// Gen start Condition

	I2C_Gen_Start(pI2Chandle->pI2Cx);
	// Confirm that the start condition is generated by checking the SB flag in the SR1
	//Until SB is cleared SCL will b stretched (pulled to low)
	while(I2C_GetFlagStatus(pI2Chandle->pI2Cx , I2C_FLAG_SB) == 0); // wait till SB is set
	// Send the address of the slave with read write bit set to write(0) total 8 bits
	I2C_ExecuteAddressPhase(pI2Chandle->pI2Cx,SlaveAddr);

	// check the address phase is completed by checking the ADDR flag in the status register
	while(I2C_GetFlagStatus(pI2Chandle->pI2Cx , I2C_FLAG_ADDR) == 0);
	ClearAddrFlag(pI2Chandle);
	// Send Data until length becomes zero
	while(Len>0)
	{
		while(I2C_GetFlagStatus(pI2Chandle->pI2Cx , I2C_FLAG_TXE) == 0); //wait till TXE is set
		pI2Chandle->pI2Cx->I2C_DR = *pTxBuffer;
		Len--;
		pTxBuffer++;

	}
	while(I2C_GetFlagStatus(pI2Chandle->pI2Cx , I2C_FLAG_TXE) == 0); // wait till TXE is set
	while(I2C_GetFlagStatus(pI2Chandle->pI2Cx , I2C_FLAG_BTF) == 0); // wait till BTF is set
	if(rep_start == REP_START_DISABLE)
	I2C_Gen_Stop(pI2Chandle->pI2Cx);




}
void I2C_MasterReceiveData(I2C_handle_t *pI2Chandle, uint8_t *pRxBuffer ,uint32_t Len, uint8_t SlaveAddr,uint8_t rep_start)
{
	//First step is to generate start condition
	I2C_Gen_Start(pI2Chandle->pI2Cx); // generates start condition
	 // wait for the SB to be set which indicates start condition completion
	while(I2C_GetFlagStatus(pI2Chandle->pI2Cx,I2C_FLAG_SB) == 0);
	I2C_ExecuteAddressPhaseRead(pI2Chandle->pI2Cx, SlaveAddr);
	// wait for address phase to complete
	while(I2C_GetFlagStatus(pI2Chandle->pI2Cx,I2C_FLAG_ADDR) == 0);
	// receive phase started
	if(Len == 1)
		{
			//Disable Acking
		   pI2Chandle->pI2Cx->I2C_CR1 &= ~(1 << I2C_ACK); //Disable ACKING
			//I2C_Gen_Stop(pI2Chandle->pI2Cx);

			//clear the ADDR flag
		   ClearAddrFlag(pI2Chandle);

			//wait until  RXNE becomes 1
			while(! I2C_GetFlagStatus(pI2Chandle->pI2Cx,I2C_FLAG_RXNE) );

			//generate STOP condition
			if(rep_start  == REP_START_DISABLE)
			I2C_Gen_Stop(pI2Chandle->pI2Cx);


			//read data in to buffer
			*pRxBuffer = pI2Chandle->pI2Cx->I2C_DR;

		}
	else if(Len > 1)
	{
	while(Len>0)
		{
		    ClearAddrFlag(pI2Chandle);
			while(I2C_GetFlagStatus(pI2Chandle->pI2Cx , I2C_FLAG_RXNE) == 0); //wait till RXE is set

			if(Len == 2) // meaning the byte code is going to read is the  first last second byte
				// before reading the last second byte we have to set ACK to 0 set the bit for stop request and then clear the RXE by reading DR
				// refer the the transfer sequence (204)
			{
				 pI2Chandle->pI2Cx->I2C_CR1 &= ~(1 << I2C_ACK); //Disable ACKING
				 if(rep_start == REP_START_DISABLE)
				 pI2Chandle->pI2Cx->I2C_CR1 |= (1 << I2C_STOP);// set the stop

				*pRxBuffer = pI2Chandle->pI2Cx->I2C_DR;
				 Len--;
				 pRxBuffer++;
			}
			else
			{
			*pRxBuffer = pI2Chandle->pI2Cx->I2C_DR;
			Len--;
			pRxBuffer++;
			}

		}
	}

	pI2Chandle->pI2Cx->I2C_CR1 |= (1 << I2C_ACK);


}
static void I2C_Gen_Start(I2C_RegDef_t *pI2Cx)
{
	pI2Cx->I2C_CR1|= (1 << I2C_START);
}
uint8_t I2C_GetFlagStatus(I2C_RegDef_t* pI2Cx,uint32_t FlagName)
{
	if(pI2Cx->I2C_SR1 & FlagName)
	{
		return(1);
	}
		return(0);

}
static void I2C_ExecuteAddressPhase(I2C_RegDef_t *pI2Cx,uint8_t SlaveAddr)
{
	SlaveAddr = SlaveAddr << 1;
	SlaveAddr &= ~(1<<0);
	pI2Cx->I2C_DR = SlaveAddr;

}
static void I2C_ExecuteAddressPhaseRead(I2C_RegDef_t *pI2Cx,uint8_t SlaveAddr)
{
	SlaveAddr = SlaveAddr << 1;
	SlaveAddr |= (1<<0);
	pI2Cx->I2C_DR = SlaveAddr;
}
static void ClearAddrFlag(I2C_handle_t *pI2Chandle)
{
	 uint32_t dummy_read;
	if(pI2Chandle->pI2Cx->I2C_SR2 & (1 << I2C_MSL)) // set meaning the I2C is in master mo0de
	{
		if(pI2Chandle->TxRx_status == I2C_BUSY_IN_RX)
		{
			if(pI2Chandle->RxSize == 1)
			{
				//disable the ACK
				 pI2Chandle->pI2Cx->I2C_CR1 &= ~(1 << I2C_ACK);
				// clear the ADDR flag
				 dummy_read = pI2Chandle->pI2Cx->I2C_SR1; //first read SR1
				 dummy_read = pI2Chandle->pI2Cx->I2C_SR2; //
			}
			else
			{
				dummy_read = pI2Chandle->pI2Cx->I2C_SR1; //first read SR1
				dummy_read = pI2Chandle->pI2Cx->I2C_SR2; //
			}
		}
		else
		{
			dummy_read = pI2Chandle->pI2Cx->I2C_SR1; //first read SR1
			dummy_read = pI2Chandle->pI2Cx->I2C_SR2; //
		}
	}
	else
	{
		//slave mode
		dummy_read = pI2Chandle->pI2Cx->I2C_SR1; //first read SR1
        dummy_read = pI2Chandle->pI2Cx->I2C_SR2; //
	}
}
static void I2C_Gen_Stop(I2C_RegDef_t *pI2Cx)
{
	pI2Cx->I2C_CR1|= (1 << I2C_STOP);
}
static void EnDi_Interrupts(I2C_RegDef_t *pI2Cx , uint8_t EnDi)
{
	if(EnDi == ENABLE)
	{
		pI2Cx->I2C_CR2 |= (1 << I2C_ITBUFEN);
		pI2Cx->I2C_CR2 |= (1 << I2C_ITEVTEN); // SETS itbufen and itevten bits
	}
	else if (EnDi == DISABLE)
	{
		pI2Cx->I2C_CR2 &= ~(1 << I2C_ITBUFEN);
		pI2Cx->I2C_CR2 &= ~(1 << I2C_ITEVTEN);
	}
}
//Interrupt enabled data transfer
// returns the state to the application code
uint8_t I2C_MasterReceiveDataIT(I2C_handle_t *pI2Chandle, uint8_t *pRxBuffer ,uint32_t Len, uint8_t SlaveAddr , uint8_t rep_start)
{
	/*In This function we will only initialize the I2C handle with the data that is passed ass
	 * parameters from  the application layer code
	 */
	uint8_t state = pI2Chandle->TxRx_status;
	if(state != I2C_BUSY_IN_TX && state != I2C_BUSY_IN_RX )
	{
	pI2Chandle->RxLen = Len;
	pI2Chandle->pRxBuffer = pRxBuffer;
	pI2Chandle->Slaveaddr = SlaveAddr;
	pI2Chandle->TxRx_status = I2C_BUSY_IN_RX;
	pI2Chandle->Sr = rep_start; // if zero no rp start

	I2C_Gen_Start(pI2Chandle->pI2Cx);
	//Enable interrupt for TX
	EnDi_Interrupts(pI2Chandle->pI2Cx , ENABLE);// will cause an interrupt for SB first
}
	return(state);
}
uint8_t I2C_MasterSendDataIT(I2C_handle_t *pI2Chandle, uint8_t *pTxBuffer ,uint32_t Len, uint8_t SlaveAddr , uint8_t rep_start)
{
	/*In This function we will only initialize the I2C handle with the data that is passed ass
	 * parameters from  the application layer code
	 */
	//uint8_t state = I2Chandle->TxRx_status;
	if(pI2Chandle->TxRx_status!= I2C_BUSY_IN_TX && pI2Chandle->TxRx_status != I2C_BUSY_IN_RX )
	{
	pI2Chandle->TxLen = Len;
	pI2Chandle->pTxBuffer = pTxBuffer;
	pI2Chandle->Slaveaddr = SlaveAddr;
	pI2Chandle->TxRx_status = I2C_BUSY_IN_TX;
	pI2Chandle->Sr = rep_start; // if zero no rp start
	I2C_Gen_Start(pI2Chandle->pI2Cx);
	pI2Chandle->pI2Cx->I2C_CR2 |= (1 << I2C_ITBUFEN);
	pI2Chandle->pI2Cx->I2C_CR2 |= (1 << I2C_ITEVTEN);


	//Enable interrupt for TX

}
	return(pI2Chandle->TxRx_status);
}

void I2C_EV_IRQHandling(I2C_handle_t *pI2Chandle)
{
    uint32_t temp1, temp2 , temp3;
    //interrupt handling for both master and slave mode of device
    //Handle for interrupt generated by SB event
    //Note SB flag is applicablr for Master mode
    temp1 = pI2Chandle->pI2Cx->I2C_CR2 & (1 << I2C_ITEVTEN);
    temp2 = pI2Chandle->pI2Cx->I2C_CR2 & (1 << I2C_ITBUFEN);
    temp3 = I2C_GetFlagStatus(pI2Chandle->pI2Cx , I2C_FLAG_SB);

    if(temp1 && temp3) // only then the interrupt is caused by SB flag
    {
    	//if control reaches here SB event has occured
    	if(pI2Chandle->TxRx_status ==I2C_BUSY_IN_TX )
    	{
    		I2C_ExecuteAddressPhase(pI2Chandle->pI2Cx,pI2Chandle->Slaveaddr);
    	}
    	else if(pI2Chandle->TxRx_status ==I2C_BUSY_IN_RX )
    	{
    		I2C_ExecuteAddressPhaseRead(pI2Chandle->pI2Cx,pI2Chandle->Slaveaddr);
    	}

    }
    // Hnadle interrupt for ADDR event
    //when in master mode Address is sent and ACK is recvd from slave setting the ADDR bit in SR1 and causing the interrupt
    temp3 = I2C_GetFlagStatus(pI2Chandle->pI2Cx , I2C_FLAG_ADDR);

    if (temp1 && temp3) // ADDR EVENT
    {
    	ClearAddrFlag(pI2Chandle);
    }

    temp3 = I2C_GetFlagStatus(pI2Chandle->pI2Cx , I2C_FLAG_BTF);
    if (temp1 && temp3) // BTF
    {
    	/*
    	 * whenever the BTF flag is set if TXE is salso set it means both SHIFT REG AND DATA REG ARE EMPTY During transmission
    	 *
    	 */

    	if(pI2Chandle->TxRx_status ==I2C_BUSY_IN_TX )
    	{
    		if(I2C_GetFlagStatus(pI2Chandle->pI2Cx , I2C_FLAG_BTF) == 1)
    		{
    			// control reached here meaning both TXE and BTF set
    			if(pI2Chandle->TxLen==0)
    			{
    			// Generate stop codition
    			if(pI2Chandle->Sr == REP_START_DISABLE )
    			{
    				I2C_Gen_Stop(pI2Chandle->pI2Cx);
    			}

    			// Reset all the member elements of the handle structure
    			I2C_CloseSendData(pI2Chandle);

    			//notify the application transfer is complete
    			I2C_ApplicationEventCallback(pI2Chandle, I2C_EV_TX_CMPLT);
    			}
    		}
    	}

    }
    temp3 = I2C_GetFlagStatus(pI2Chandle->pI2Cx , I2C_FLAG_STOPF);
    if (temp1 && temp3) // STOPF
    {
    	/*
    	 * When the stm32 is in slave mode
    	 * when a stop condition is detected by slave mode stm then this bit is set
    	 * Clear the STOPF first read SR1 then write to CR1
    	 */
    	pI2Chandle->pI2Cx->I2C_CR1 |= 0x0000;
    	//notify the application STOP IS DETECTED
    	I2C_ApplicationEventCallback(pI2Chandle, EVENT_STOP);

    }
    //rEFER ppt
    /*
     * In the interrupt table e it is mentioned that when EV_8 TXE=1 interrupt occurs when TXE= 1 IEVNT =1 AND itbufen FLAG IS SET
     */
    temp3 = I2C_GetFlagStatus(pI2Chandle->pI2Cx , I2C_FLAG_TXE);
    if(temp1 && temp2 && temp3)
    {
    	//EV_8 to put the next data byte in the DR register
        if(pI2Chandle->pI2Cx->I2C_SR2 & (1 << I2C_MSL))
        {


    	if(pI2Chandle->TxRx_status == I2C_BUSY_IN_TX )
    	{
    		I2CMasterHandleTXEInterrupt(pI2Chandle);
    	}

    }
    }
    temp3 = I2C_GetFlagStatus(pI2Chandle->pI2Cx , I2C_FLAG_RXNE);
        if(temp1 && temp2 && temp3)
        {
        	I2CMasterHandleRXNEInterrupt(pI2Chandle);
        }

}

static void I2CMasterHandleTXEInterrupt(I2C_handle_t *pI2Chandle)
{
	if(pI2Chandle->TxLen > 0)
	{
		// put data in data reg
		pI2Chandle->pI2Cx->I2C_DR = *(pI2Chandle->pTxBuffer);//

		// Decrement the TXLEN
		pI2Chandle->TxLen -- ;
		//Increment the pointer storing the buffer address to point to next location
		pI2Chandle->pTxBuffer ++;
	}
}
static void I2CMasterHandleRXNEInterrupt(I2C_handle_t *pI2Chandle)
{


	     if(pI2Chandle->pI2Cx->I2C_SR2 & (1 << I2C_MSL))
	        {

	        if(pI2Chandle->TxRx_status == I2C_BUSY_IN_RX )
	        {
	        if(pI2Chandle->RxSize == 1)
	        {
	        		//first disable the ACKING before clearing the ADDR flag as per the transfer seq
	        	*(pI2Chandle->pRxBuffer) = pI2Chandle->pI2Cx->I2C_DR;
	        	pI2Chandle->RxLen --;

	        }
	        if(pI2Chandle->RxSize > 0)
	        {
	           if(pI2Chandle->RxLen == 2)
	            {
	            	  pI2Chandle->pI2Cx->I2C_CR1 &= ~(1 << I2C_ACK);
	            }
	        			// put data in data reg
	        		*(pI2Chandle->pRxBuffer)= pI2Chandle->pI2Cx->I2C_DR ;

	        			// Decrement the RXLEN
	        		pI2Chandle->RxLen -- ;
	        			//Increment the pointer storing the buffer address to point to next location
	        		pI2Chandle->pRxBuffer ++;
	        }
	         if(pI2Chandle->RxLen == 0)
	            {
	            		//close data reception and notify application

	            		//gen stop
	             if(pI2Chandle->Sr == REP_START_DISABLE )
	            	{
	            		    I2C_Gen_Stop(pI2Chandle->pI2Cx);
	            	 }
	             I2C_CloseReceiveData(pI2Chandle);

	            		//Notify APP
	            I2C_ApplicationEventCallback(pI2Chandle , I2C_EV_RX_CMPLT);
	            	}
	        	}

	        }
}
static void I2C_CloseSendData(I2C_handle_t* pI2Chandle)
{
	pI2Chandle ->pI2Cx->I2C_CR2 &=~(1 << I2C_ITBUFEN);
	pI2Chandle ->pI2Cx->I2C_CR2 &=~(1 << I2C_ITEVTEN);

	pI2Chandle->TxRx_status = I2C_READY;
	pI2Chandle->pTxBuffer = NULL;
	pI2Chandle->RxLen=0;
	pI2Chandle->TxLen=0;
	pI2Chandle->RxSize=0;
	 pI2Chandle->pI2Cx->I2C_CR1 |=(1 << I2C_ACK);



}
static void I2C_CloseReceiveData(I2C_handle_t *pI2Chandle)
{
	pI2Chandle ->pI2Cx->I2C_CR2 &=~(1 << I2C_ITBUFEN);
	pI2Chandle ->pI2Cx->I2C_CR2 &=~(1 << I2C_ITEVTEN);

	pI2Chandle->TxRx_status = I2C_READY;
	pI2Chandle->pRxBuffer = NULL;
	pI2Chandle->RxLen=0;
	pI2Chandle->TxLen=0;
	pI2Chandle->RxSize=0;
	pI2Chandle->pI2Cx->I2C_CR1 |=(1 << I2C_ACK);
}
void I2C_IRQConfig(uint8_t IRQNumber,uint8_t EnDi)
{
	// identify IRQ number based on the pin number for PA0 it will be EXTI0 identify on which IRQ line it issues interrupt
	//first set the priority of the interrupt then enable the interrupt

	volatile uint32_t* ISER = (uint32_t*) NVIC_ISER_BASEADDR;

	volatile uint32_t* ICER = (uint32_t*)NVIC_ICER_BASEADDR;

	uint32_t ISER_reg_offset;
	uint32_t ISER_reg_bit_pos;

	uint32_t ICER_reg_offset;
	uint32_t ICER_reg_bit_pos;

	ISER_reg_offset = IRQNumber/32;
	ISER_reg_bit_pos = IRQNumber%32;

	ICER_reg_offset = ISER_reg_offset;
	ICER_reg_bit_pos = ISER_reg_bit_pos;

	if (EnDi == ENABLE)
	{
		ISER = ISER + ISER_reg_offset;
	    *ISER|=(1<<ISER_reg_bit_pos); // enable the interrupt
	}
	else if (EnDi == DISABLE)
	{
			ICER = ICER + ICER_reg_offset;
			*ICER|=(1 << ICER_reg_bit_pos);

	}
}
